services:
  - type: web
    name: readwell
    env: node
    buildCommand: npm --prefix server install && npm --prefix client install && npm --prefix client run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PGSSL
        value: true
      - key: SESSION_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        value: https://readwell-gjoj.onrender.com/api/auth/github/callback
      - key: CLIENT_URL
        value: https://readwell-gjoj.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: readwell-db
          property: connectionString

databases:
  - name: readwell-db
